name: Update Tag on Push

on:
  push:
    branches:
      - main  # You can change this to your main branch name

jobs:
  update_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Delete Previous Tag
      run: |
        git fetch --tags
        git tag -d v2
        git push --delete origin v2

    - name: Create New Tag
      run: |
        git tag -a v2 -m "Tag"
        git push origin --tags

    - name: Build Docker Image
      run: |
        cd client && ./docker.sh

