name: Create Tag on Push

on:
  push:
    branches:
      - main  # You can change this to your main branch name

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Create Tag
      run: |
        git tag -a v${{ github.run_number }} -m "Tag"
        git push origin --tags
